[package]
name = "zengine_window"
version = "0.1.0"
edition = "2021"

[dependencies]
zengine_ecs = { path = "../zengine_ecs" }
zengine_engine = { path = "../zengine_engine" }
zengine_input = { path = "../zengine_input" }
zengine_macro = { path = "../zengine_macro" }
serde = { version = "1.0", features = ["derive"] }
cfg-if = "1"
log = "0.4"
rustc-hash = "1.1.0"
winit = "0.27.3"
glam = "0.21.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1.1"
jni = "0.19.0"