[package]
name = "zengine_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sdl2 = { version = "0.33.0", features = ["bundled", "static-link"] }