[package]
name = "zengine_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
zengine_ecs = { path = "../zengine_ecs" }
serde = { version = "1.0", features = ["derive"] }
sdl2 = { version = "0.33.0", features = ["bundled", "static-link"] }
log = "0.4"
rustc-hash = "1.1.0"