[package]
name = "pong"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zengine = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
fastrand = "1.4.1"
serde_yaml = "0.8"