[package]
name = "zengine_input"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
fnv = "1.0.7"
log = "0.4"
sdl2 = { version = "0.33.0", features = ["bundled", "static-link"] }
zengine_platform = { path = "../zengine_platform" }
zengine_ecs = { path = "../zengine_ecs" }
zengine_engine = { path = "../zengine_engine" }

[dev-dependencies]
serde_yaml = "0.8"