[package]
name = "zengine_physics"
version = "0.1.0"
edition = "2021"

[dependencies]
zengine_ecs = { path = "../zengine_ecs" }
zengine_core = { path = "../zengine_core" }
zengine_macro = { path = "../zengine_macro" }
log = "0.4"
rustc-hash = "1.1.0"
glam = "0.21.3"
