[package]
name = "zengine"
version = "0.1.0"
edition = "2018"

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.33.0", features = ["bundled", "static-link"] }
auto_ops = "0.1.0"
image = "0.22.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"