[package]
name = "zengine"
version = "0.1.0"
edition = "2018"

[dependencies]
gl = "0.14.0"
sdl2 = { version = "0.33.0", features = ["bundled", "static-link"] }
auto_ops = "0.1.0"
image = "0.23.4"
downcast-rs = "1.1.1"